version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
commands:
  - docker -v
  - docker run -d -p 85:80 httpd
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root
